config/routes.rb
Bbchatter::Application.routes.draw do

  # Nested resources for creating & fetching messages
  match 'chatrooms/:room_key/messages' => 'messages#index', :via => :get
  match 'chatrooms/:room_key/messages' => 'messages#create', :via => :post

  match 'chatrooms' => 'chatrooms#create', :via => :post
  match 'chatrooms/:room_key/join' => 'chatrooms#join', :via => :post
  
  match 'about' => 'home#about', :via => :get
  match 'qunit' => 'tests#qunit', :via => :get
  
  root :to => 'home#index'

end

app/models/chat_room.rb
class ChatRoom
  has_many :messages, :class_name => "chat_message"
  set_primary_key 'uuid'
  before_create :generate_uuid

  def generate_uuid
    self.id = UUIDTools::UUID.random_create.to_s
  end

  # uuid
  # room_name
  # room_key
  # created_by
end

app/models/chatroom.rb
require 'random_string_generator'

class Chatroom < ActiveRecord::Base
	attr_accessible :room_name

  has_many :messages, dependent: :destroy
  
  validates_presence_of :room_name

  before_create :set_room_key

  KEY_LENGTH = 20

  def self.destroy_all_older_than(duration_in_seconds)
    since = Time.now.utc - duration_in_seconds
    condition = "updated_at < '#{since}'"
    self.destroy_all condition
  end

  def set_room_key
  	self.room_key = RandomStringGenerator.generate_string KEY_LENGTH
  end

end

# id: integer
# room_key: string
# room_name: string
# created_at: datetime
# updated_at: datetime

app/models/message.rb
class Message < ActiveRecord::Base

  # Associations
  belongs_to :chatroom

  # Validations
  validates_presence_of :display_name
  validates_presence_of :text

  LATEST_DURATION_IN_SECONDS = 10

  def self.find_latest(message_ids = nil)
    since = Time.now - LATEST_DURATION_IN_SECONDS
    message_ids = [-1] unless message_ids && !message_ids.empty?
    self.where("created_at >= ? and id not in (?)", since, message_ids)
  end

  def with_new_values(params)
  	raise "Unable to set values on existing record" unless new_record?

  	self.text = params[:text]
  	self.display_name = params[:display_name]
  	self
  end

end

# id: integer
# text: text
# display_name: string
# ip_address: string
# created_at: datetime
# updated_at: datetime

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

	def index
		@chatrooms = Chatroom.all
	end

	def create
		@chatroom = Chatroom.new :room_name => params[:room_name]
		@chatroom.save!
		render :json => @chatroom, :status => :created
	end

	def join
		@chatroom = Chatroom.find_by_room_key params[:room_key] 
		if @chatroom
			render :json => @chatroom, :status => :ok
		else
			render :json => nil, :status => :notfound
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	# We're just rendering a template here. Nothing else
	# to worry about.
	def index; end

	def about; end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @room_key = params[ :room_key ]
    @messages = get_messages @room_key
    add_message_ids_to_cache @messages.map &:id

    render :json => @messages, :status => :ok
  end

  def create
    @room_key = params[ :room_key ]
    
    @chatroom = Chatroom.find_by_room_key @room_key
    @message = @chatroom.messages.build.with_new_values params
    @message.save!
    add_message_id_to_cache @message.id

    render :json => @message, :status => :created
  end

private

  def get_messages( room_key )
    chatroom = Chatroom.find_by_room_key room_key
    if chatroom
      chatroom.touch
      messages = chatroom.messages.find_latest session[:message_ids]
      messages
    else
      []
    end
  end

  def add_message_id_to_cache(message_id)
    session[:message_ids] ||= []
    session[:message_ids] << message_id
  end

  def add_message_ids_to_cache(message_ids)
    message_ids.each { |id| add_message_id_to_cache id }
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

	# Just rendering a view here. Nothing else special.
	def qunit; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/chatrooms/index.html.erb
<table class="table table-condensed">
	<thead>
		<tr>
			<th>ID</th>
			<th>Room Name</th>
			<th>Room Key</th>
		</tr>
	</thead>
	<tbody>
		<% @chatrooms.each do |c| %>
			<tr>
				<td> <%= c.id %> </td>
				<td> <%= c.room_name %> </td>
				<td> <%= c.room_key %> </td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/home/about.html.erb
<div id="about" style="margin:0;padding:30px;">

	<p>
		<%= link_to "BBChatter", root_path %> was written by 
		<%= link_to "Jarrett Meyer", "http://jarrettmeyer.com" %> as a way to learn
		<%= link_to "BackboneJS", "http://backbonejs.org" %>.
	</p>

	<p>
		Want to know more? All of the source code is available on
		<%= link_to "Github", "https://github.com/jarrettmeyer/bbchatter" %>.
	</p>


	<h2>Blog Posts</h2>

	<ul>
    <li><%= link_to("Part 1: Server-Side Models", "http://jarrettmeyer.com/blog/2012/10/25/learning-backbonejs-part-1/") %></li>
    <li><%= link_to("Part 2: Server-Side Controllers and Routes", "http://jarrettmeyer.com/blog/2012/10/29/learning-backbonejs-part-2/") %></li>
    <li><%= link_to("Part 3: Client-Side Models", "http://jarrettmeyer.com/blog/2012/10/30/learning-backbonejs-part-3/") %></li>
    <li><%= link_to("Part 4: Backbone Views", "http://jarrettmeyer.com/blog/2012/11/01/learning-backbonejs-part-4/") %></li>
    <li><%= link_to("Caching IDs", "http://jarrettmeyer.com/blog/2012/11/05/adding-cached-ids-to-bbchatter/") %></li>
	</ul>

</div>

app/views/home/index.html.erb
<div id="chatroom">
	<div id="chatroom-header">
		<div id="chatroom-name"></div>
		<div id="chatroom-key"></div>
		<div id="goto-about">
			<%= link_to about_path do %>
				<%= image_tag "information.png" %>
				About
			<% end %>
		</div>
	</div>
	<div id="chatroom-window">
		<div id="messages"></div>
	</div>
	<div id="chatroom-footer">
		<form id="chatter-form">
			<textarea id="message-text" name="message-text"></textarea>
			<button type="submit">
				Submit
			</button>
		</form>
	</div>

	<div id="overlay">
		<div class="overlay-content">
			<div>
				<label for="display_name">Your Name</label>
				<input type="text" name="display_name" id="display_name"/>
			</div>
			<div>
				<label class="radio">
					<input type="radio" name="room_type" id="room_type_join" value="join"/>
					Join an existing chatroom
				</label>
				<label class="radio">
					<input type="radio" name="room_type" id="room_type_create" value="create"/>
					Create a new chatroom
				</label>
			</div>
			<div id="room_key_fields" style="display:none;">
				<label for="room_key">Room Key</label>
				<input type="text" id="room_key" name="room_key"/>
			</div>
			<div id="room_name_fields" style="display:none;">
				<label for="room_name">Room Name</label>
				<input type="text" id="room_name" name="room_name"/>
			</div>
			<div>
				<button type="button" id="start-chatting">
					Start Chatting
				</button>
			</div>
		</div>
	</div>

</div>

<script type="text/template" id="message-template">
	<div class="message-header">
    <%%- display_name %> [<%%- timestamp %>]
  </div>
  <div class="message-body">
    <%%- text %>
  </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BBChatter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :chat_room_id %><br />
    <%= f.number_field :chat_room_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<div id="messages"></div>

<script type="text/javascript">
  $(function() {
    window.router = new bbchatter.MessageRouter({messages: <%= @messages.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @message.text %>
</p>

<p>
  <b>Display name:</b>
  <%= @message.display_name %>
</p>

<p>
  <b>Chat room:</b>
  <%= @message.chat_room_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>